### DISCUSSION TITLE
Tools / Agent Communication PreferenceS

### DISCUSSION THREAD

**Discussion by LukeLalor** [eidolon-ai/eidolon#894] [Polls]
## Today

```yaml
kind: Agent
metadata:
    name: my_soccer_researcher
spec: 
    implementation: GeneralAgent
```
```yaml
kind: Agent
metadata:
    name: chatbot
spec: 
    implementation: GeneralAgent
    agent_refs:
        - my_soccer_researcher
    apu:
        tools:
            - implementation: Calculator
              operations: ["add", "subtract"]
```

## Option 1
Show agent communication explicitly as a tool.

```yaml
kind: Agent
metadata:
    name: my_soccer_researcher
spec: 
    implementation: GeneralAgent
```
```yaml
kind: Agent
metadata:
    name: chatbot
spec: 
    implementation: GeneralAgent
    tools:
        - implementation: AgentCommunicator
          agent_name: my_soccer_researcher
        - implementation: Calculator
          operations: ["add", "subtract"]
```

## Option 2
Split out tools and agents separately.

```yaml
kind: Agent
metadata:
    name: my_soccer_researcher
spec: 
    implementation: GeneralAgent
```
```yaml
kind: Agent
metadata:
    name: chatbot
spec: 
    implementation: GeneralAgent
    references:
        - agent: my_soccer_researcher
        - tool:
            implementation: Calculator
            operations: ["add", "subtract"]
```
