### ISSUE TITLE
Check examples and samples for agent names with underscores _

### ISSUE THREAD

**Issue by flynntsang** [eidolon-ai/eidolon#702]
Following up on #690, a github search shows we still have a number of samples where agents are named underscores _ as separators. Apparently that's a no-no for K8S. Underscores should be changed to hyphens -.

- Files to change: YAML
- Files not to change: question for @dbrewster or @LukeLalor -- python classes are fine, correct?
- Files to check: docs and READMEs

**Comment by muddi900** [comment]
So is 0de3974dc0212b5c0c1872e073e6016611d76094 what you are looking for?

**Comment by flynntsang** [comment]
@muddi900 Thanks for helping out! I believe it's just the name of the agents that's the problem.

The resource (YAML) file names do not need to change, nor any python code. Just the agent metadata _in_ the resource YAML files, e.g.:

```yaml
apiVersion: eidolon/v1
kind: Agent
metadata:
  name: hello_world # this needs to change to hello-world
```

I think we got most of the `hello_world` agents, but there are a number of other examples that we haven't checked yet.

Thanks again!
