### ISSUE TITLE
[ feature ] Chain Agent

### ISSUE THREAD

**Issue by LukeLalor** [eidolon-ai/eidolon#706]
It is helpful to follow the "user story" method, but you don't have to. Delete anything you don't use to keep the issue tidy. (Like these instructions :smile:)

**User Story**
- As a developer familiar with langchain
- I want understand how to use eidolon
- So that I can do two things
  - convert my work to eidolon
  - do more with eidolon then I can with langchain

**Acceptance Criteria**
- Given that I have the tools/documentation from eidolon
- When I create an agent
- Then I can explicitly chain together actions / agents

**Comment by LukeLalor** [comment]
note, if an action allows for output format to be specified via request, this can use structured arbitrarily through the chain which would be very powerful

**Comment by LukeLalor** [comment]
It may be a different agent, but allowing chains to fork would also be powerful. IE, agent graphs

```
chain:
  - agent1
  - tool1
  - prompt: if the response "{{ output }}" does not satisfy xyz corporate policy, choose "rejection" option
     options:
       - name: rejection
         chain: [r_agent1, r_agent2]
       - name: acceptence
         chain: [a_agent1, a_agent2]
```
