### ISSUE TITLE
[ feature ] code completion: ide / text editor plugins

### ISSUE THREAD

**Issue by flynntsang** [eidolon-ai/eidolon#740]
**User Story**
- As an AI developer / AI-ops engineer
- I want to code completion when working on resource (YAML) files
- So I can accurately define specable attributes when configuring my agents

**Acceptance Criteria**
- Given that I want to customize or need to configure an agent
- When I have an Eidolon plugin for my IDE / text editor
  - IntelliJ
  - VSCode
- Then I only see the allowed attributes and sub-attributes

In the following example, it's hard to understand why there's no `implementation` directly under `apu`. If there were `apu > implementation`, would `llm_unit` be indented? Unless you have someone (or some tool) helping you, it's difficult to apply custom logic.

```yaml title=resources/your_agent_name.yaml
apiVersion: server.eidolonai.com/v1alpha1
kind: Agent
metadata:
  name: your_agent_name
spec:
  apu: 
    llm_unit: # from /docs/components/llmunit/overview
      implementation: OpenAIGPT
      model: 
        name: gpt-4o-mini # from /docs/components/llmmodel/overview
        human_name: "GPT-4o Mini" # optional
```
 

Challenge: agent templates can expose arbitrary attributes.
