### ISSUE TITLE
[ problem ] Vectara validation error 

### ISSUE THREAD

**Issue by flynntsang** [eidolon-ai/eidolon#876]
**Describe the problem**
When running the Vectara logic unit:
`APU Error: ValidationError while processing request`

**Agent YAML file**
```yaml
apiVersion: server.eidolonai.com/v1alpha1
kind: Agent
metadata:
  name: riverparkresearch
spec: 
  implementation: SimpleAgent
  apu: 
    implementation: ConversationalAPU
    logic_units:
      - implementation: VectaraSearch
        corpus_key: riverpark-chat
```
Log file attached
[logs_vectara_tool_validation_error.txt](https://github.com/user-attachments/files/17547517/logs_vectara_tool_validation_error.txt)
