### ISSUE TITLE
[ problem ] webui error with agent-machine

### ISSUE THREAD

**Issue by flynntsang** [eidolon-ai/eidolon#941]
I'm unable to get a simple agent-machine to work with the chatbot webapp. Files attached.

`agent-machine > resources > hello-world-agent.eidolon.yaml`

```yaml
apiVersion: server.eidolonai.com/v1alpha1
kind: Agent
metadata:
  name: hello-world-agent
spec:
  implementation: SimpleAgent
  description: |
    "This is a general agent that uses an LLM to answer questions."
  system_prompt: You are a helpful assistant. Always use the provided tools, if appropriate, to complete the task.
  actions:
    - name: converse
```

`agent-machine > webui.apps.json`

```yaml
{
  "chatbot": {
    "name": "Chatbot",
    "description": "A basic chatbot using GPT-4-latest with conversational memory and no tools.",
    "version": "0.1.0",
    "image": "image.webp",
    "type": "copilot",
    "params": {
      "agent": "conversational-agent",
      "operation": "converse",
      "inputLabel": "How can I help you?",
      "titleOperationName": "generate_title",
      "allowSpeech": true,
      "speechAgent": "speech-agent",
      "speechOperation": "speech_to_text"
    }
  },
  "dev-tool": {
    "name": "Eidolon Developer Tool",
    "description": "The developer tools can be used to test and debug any Eidolon operation.",
    "image": "image.webp",
    "type": "dev",
    "params": {}
  }
}
```

Server output starting with `make docker-serve`
[error-agent-machine-webui.txt](https://github.com/user-attachments/files/17938047/error-agent-machine-webui.txt)
