### ISSUE TITLE
[ problem ] found unhashable key in resource `user_prompt: {{ body }}`

### ISSUE THREAD

**Issue by flynntsang** [eidolon-ai/eidolon#944]
**To Reproduce**

1. Clone the agent-machine
2. Create a new agent resource file, e.g. `hello-world-agent.eidolon.yaml`
3. Use the IDE shortcuts, e.g.:
  - `apiVersion`
  - `AgentResource`
  - `SimpleAgent`
  - `actions`
4. Add or edit the configuration so you get the following file:
```yaml
apiVersion: server.eidolonai.com/v1alpha1
kind: Agent
metadata:
  name: hello-world-agent
spec:
  implementation: SimpleAgent
  actions:
    - name: converse
      user_prompt: {{ body }}
      allow_file_upload: true
      output_state: idle
```
5. From the agent-machine root directory, load the server, e.g. `sudo make docker-serve`
6. See error (attached)

```
...
agent-server-1  |   File "/usr/local/lib/python3.11/site-packages/yaml/constructor.py", line 141, in construct_mapping
agent-server-1  |     raise ConstructorError("while constructing a mapping", node.start_mark,
agent-server-1  | yaml.constructor.ConstructorError: while constructing a mapping
agent-server-1  |   in "/local_mount/resources/hello-world-agent.eidolon.yaml", line 9, column 20
agent-server-1  | found unhashable key
agent-server-1  |   in "/local_mount/resources/hello-world-agent.eidolon.yaml", line 9, column 21
```

[error-action-body-unhashable-key.txt](https://github.com/user-attachments/files/17940395/error-action-body-unhashable-key.txt)

**Comment by flynntsang** [comment]
@LukeLalor Quoting prevents an error, specifically: `"{{ body }}"`

To do: update the IDE plugins.

```yaml
apiVersion: server.eidolonai.com/v1alpha1
kind: Agent
metadata:
  name: hello-world-agent
spec: 
  implementation: SimpleAgent
  description: |
    "This is a general agent that uses an LLM to answer questions."
  system_prompt: You are a helpful assistant. Always use the provided tools, if appropriate, to complete the task.
  actions:
    - name: converse
      user_prompt: "{{ body }}"
      allow_file_upload: true
      output_state: idle
```
